name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn pandas httpx pytest requests
      
    - name: Ensure CSV Data is Available
      run: |
        ls -la data/
        if [ ! -f "data/users_data.csv" ] || [ ! -f "data/cards_data.csv" ]; then
          echo "Missing CSV files in /data. Check your repository."
          exit 1
        fi

    - name: Start FastAPI Server
      run: |
        uvicorn app.main:app --host 127.0.0.1 --port 8000 &
        sleep 5  # Give the server time to start

    - name: Run API Tests
      run: pytest tests/

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: najiha2002/dashboard
        tag: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    # ========== Rollback on Failure ==========
    - name: Verify Deployment & Rollback if Needed
      run: |
        STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8000/health)
        if [ "$STATUS_CODE" -ne 200 ]; then
          echo "❌ Deployment failed! Rolling back to the previous version..."
          PREVIOUS_VERSION=$(docker images najiha2002/dashboard --format "{{.Tag}}" | sort -r | sed -n '2p')
          if [ -n "$PREVIOUS_VERSION" ]; then
            docker tag najiha2002/dashboard:$PREVIOUS_VERSION najiha2002/dashboard:latest
            docker push najiha2002/dashboard:latest
          else
            echo "⚠️ No previous version found. Rollback not possible."
          fi
          exit 1
        fi
